import { Page } from "./models";

export const mockData: Page[] = [
    {
        n: "1r",
        notes: [
            {
                type: "Miniatura Rubricata",
                place: "margine lato dx",
                head: "La nascita di Alessandro",
                line: [
                    {
                        id: "t146",
                        lemma: "le",
                        pos: "DETdef",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "Li",
                    },
                    {
                        id: "t147",
                        lemma: "jor",
                        pos: "NOMcom",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "jor",
                    },
                    {
                        id: "t148",
                        lemma: "que2",
                        pos: "PROrel",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "qu&#39;",
                    },
                    {
                        id: "t149",
                        lemma: "Alexandre",
                        pos: "NOMpro",
                        msd: "NOMB.=s|GENRE=m|CAS=n",
                        text: "Alexandre",
                    },
                    {
                        id: "t150",
                        lemma: "naistre",
                        pos: "VERcjg",
                        msd: "MODE=ind|TEMPS=psp|PERS.=3|NOMB.=s",
                        text: "nasqui",
                    },
                    {
                        id: "t151",
                        lemma: "estre1",
                        pos: "VERcjg",
                        msd: "MODE=ind|TEMPS=psp|PERS.=3|NOMB.=p",
                        text: "furent",
                    },
                    {
                        id: "t152",
                        lemma: "le",
                        pos: "DETdef",
                        msd: "NOMB.=p|GENRE=m|CAS=n",
                        text: "li",
                    },
                    {
                        id: "t153",
                        lemma: "signe1",
                        pos: "NOMcom",
                        msd: "NOMB.=p|GENRE=m|CAS=n",
                        text: "signes",
                    },
                    {
                        id: "t154",
                        lemma: "en1",
                        pos: "PRE",
                        msd: "MORPH=empty",
                        text: "en",
                    },
                    {
                        id: "t155",
                        lemma: "ciel",
                        pos: "NOMcom",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "ciel",
                    },
                    {
                        id: "t156",
                        lemma: ".",
                        pos: "PONfrt",
                        msd: "MORPH=empty",
                        text: ".",
                    },
                ],
            },
            {
                type: "miniatura_rubricata",
                place: "margine lato dx",
                head:
                    "Gli altri fanciulli che nacquero lo stesso giorno di Alessandro",
                line: [
                    {
                        id: "t166",
                        lemma: "de",
                        pos: "PRE",
                        msd: "MORPH=empty",
                        text: "De",
                    },
                    {
                        id: "t167",
                        lemma: "trente",
                        pos: "DETcar",
                        msd: "NOMB.=p|GENRE=m|CAS=r",
                        text: "XXX",
                    },
                    {
                        id: "t168",
                        lemma: "fil2",
                        pos: "NOMcom",
                        msd: "NOMB.=p|GENRE=m|CAS=r",
                        text: "fil",
                    },
                    {
                        id: "t169",
                        lemma: "de",
                        pos: "PRE",
                        msd: "MORPH=empty",
                        text: "de",
                    },
                    {
                        id: "t170",
                        lemma: "contor1",
                        pos: "NOMcom",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "contor",
                    },
                    {
                        id: "t171",
                        lemma: "que2",
                        pos: "PROrel",
                        msd: "NOMB.=p|GENRE=m|CAS=n",
                        text: "que",
                    },
                    {
                        id: "t172",
                        lemma: "naistre",
                        pos: "VERcjg",
                        msd: "MODE=ind|TEMPS=psp|PERS.=3|NOMB.=p",
                        text: "nasquirent",
                    },
                    {
                        id: "t173",
                        lemma: "en1",
                        pos: "PRE",
                        msd: "MORPH=empty",
                        text: "en",
                    },
                    {
                        id: "t174",
                        lemma: "icel",
                        pos: "DETdem",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "icel",
                    },
                    {
                        id: "t175",
                        lemma: "jor",
                        pos: "NOMcom",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "jor",
                    },
                    {
                        id: "t176",
                        lemma: "que2",
                        pos: "PROrel",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "que",
                    },
                    {
                        id: "t177",
                        lemma: "naistre",
                        pos: "VERcjg",
                        msd: "MODE=ind|TEMPS=psp|PERS.=3|NOMB.=s",
                        text: "nasqui",
                    },
                    {
                        id: "t178",
                        lemma: "Alexandre",
                        pos: "NOMpro",
                        msd: "NOMB.=s|GENRE=m|CAS=r",
                        text: "Alexandre",
                    },
                    {
                        id: "t179",
                        lemma: ".",
                        pos: "PONfrt",
                        msd: "MORPH=empty",
                        text: ".",
                    },
                    {
                        id: "t179",
                        lemma: ".",
                        pos: "PONfrt",
                        msd: "MORPH=empty",
                        text: ".",
                    },
                ],
            },
        ],
        lassas: [
            {
                n: "1",
                verses: [
                    {
                        num: 1,
                        line: [
                            {
                                id: "t3c1a",
                                lemma: "conte2",
                                pos: "NOMcom",
                                msd: "NOMB.=s|GENRE=m|CAS=r",
                                text: "Conte",
                            },
                            {
                                id: "t4c1a",
                                lemma: "voloir",
                                pos: "VERcjg",
                                msd: "MODE=ind|TEMPS=pst|PERS.=1|NOMB.=s",
                                text: "voil",
                            },
                            {
                                id: "t5c1a",
                                lemma: "dire",
                                pos: "VERinf",
                                msd: "MORPH=empty",
                                text: "dire",
                            },
                            {
                                id: "t6c1a",
                                lemma: "par",
                                pos: "NOMcom",
                                msd: "NOMB.=s",
                                text: "per",
                            },
                            {
                                id: "t7c1a",
                                lemma: "rime4",
                                pos: "NOMcom",
                                msd: "NOMB.=p|GENRE=f|CAS=r",
                                text: "rime",
                            },
                            {
                                id: "t8c1a",
                                lemma: "et",
                                pos: "CONcoo",
                                msd: "MORPH=empty",
                                text: "e",
                            },
                            {
                                id: "t9c1a",
                                lemma: "par",
                                pos: "PRE",
                                msd: "NOMB.=s",
                                text: "per",
                            },
                            {
                                id: "t10c1a",
                                lemma: "lëonime",
                                pos: "NOMcom",
                                msd: "NOMB.=p|GENRE=f|CAS=r",
                                text: "leonine",
                            },
                        ],
                    },
                    {
                        num: 2,
                        line: [
                            {
                                id: "t12c1a",
                                lemma: "de+le",
                                pos: "PRE.DETdef",
                                msd: "NOMB.=s|GENRE=m|CAS=r",
                                text: "Del",
                            },
                            {
                                id: "t13c1a",
                                lemma: "fil2",
                                pos: "NOMcom",
                                msd: "NOMB.=s|GENRE=m|CAS=r",
                                text: "fil",
                            },
                            {
                                id: "t14c1a",
                                lemma: "Felipe",
                                pos: "NOMpro",
                                msd: "NOMB.=s|GENRE=m|CAS=r",
                                text: "Felipe",
                            },
                            {
                                id: "t15c1a",
                                lemma: "le",
                                pos: "DETdef",
                                msd: "NOMB.=s|GENRE=m|CAS=r",
                                text: "le",
                            },
                            {
                                id: "t16c1a",
                                lemma: "roi2",
                                pos: "NOMcom",
                                msd: "NOMB.=s|GENRE=m|CAS=r",
                                text: "roi",
                            },
                            {
                                id: "t17c1a",
                                lemma: "de",
                                pos: "PRE",
                                msd: "MORPH=empty",
                                text: "de",
                            },
                            {
                                id: "t18c1a",
                                lemma: "Macedoine",
                                pos: "NOMpro",
                                msd: "NOMB.=s|GENRE=f|CAS=r",
                                text: "Macedoine",
                            },
                        ],
                    },
                    {
                        num: 9,
                        line: [
                            {
                                id: "t66c1a",
                                lemma: "morir",
                                pos: "VERinf",
                                msd: "MORPH=empty",
                                text: "Morir",
                            },
                            {
                                id: "t67c1a",
                                lemma: "il",
                                pos: "PROper",
                                msd: "PERS.=3|NOMB.=s|GENRE=f|CAS=r",
                                text: "l’",
                            },
                            {
                                id: "t68c1a",
                                lemma: "estovoir1",
                                pos: "VERcjg",
                                msd: "MODE=ind|TEMPS=pst|PERS.=3|NOMB.=s",
                                text: "estut",
                            },
                            {
                                id: "t69c1a",
                                lemma: "ainz",
                                pos: "ADVgen",
                                msd: "MORPH=empty",
                                text: "ainz",
                            },
                            {
                                id: "t70c1a",
                                lemma: "ne1",
                                pos: "ADVneg",
                                msd: "MORPH=empty",
                                text: "ne",
                            },
                            {
                                id: "t71c1a",
                                lemma: "estre1",
                                pos: "VERcjg",
                                msd: "MODE=ind|TEMPS=psp|PERS.=3|NOMB.=s",
                                text: "fu",
                            },
                            {
                                id: "t72c1a",
                                lemma: "prendre",
                                pos: "VERppe",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: {
                                    original: "pris",
                                    regularization: "prise",
                                },
                            },
                            {
                                id: "t73c1a",
                                lemma: "essoigne",
                                pos: "NOMcom",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: "essoine",
                            },
                            {
                                id: "t74c1a",
                                lemma: ":",
                                pos: "PONfbl",
                                msd: "MORPH=empty",
                                text: ":",
                            },
                        ],
                    },
                ],
            },
            {
                n: "2",
                verses: [
                    {
                        num: 11,
                        line: [
                            {
                                id: "t86c1a",
                                lemma: "traire",
                                pos: "VERppe",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: "Traite",
                            },
                            {
                                id: "t87c1a",
                                lemma: "estre1",
                                pos: "VERcjg",
                                msd: "MODE=ind|TEMPS=pst|PERS.=3|NOMB.=s",
                                text: "est",
                            },
                            {
                                id: "t88c1a",
                                lemma: "de",
                                pos: "PRE",
                                msd: "MORPH=empty",
                                text: "de",
                            },
                            {
                                id: "t89c1a",
                                lemma: "geste2",
                                pos: "NOMcom",
                                msd: "NOMB.=s|GENRE=f|CAS=r",
                                text: "geste",
                            },
                            {
                                id: "t90c1a",
                                lemma: "tot",
                                pos: "DETind",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: "tote",
                            },
                            {
                                id: "t91c1a",
                                lemma: "cest",
                                pos: "DETdem",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: "ceste",
                            },
                            {
                                id: "t92c1a",
                                lemma: "chançon",
                                pos: "NOMcom",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: "chançon",
                            },
                            {
                                id: "t93c1a",
                                lemma: ",",
                                pos: "PONfbl",
                                msd: "MORPH=empty",
                                text: ",",
                            },
                        ],
                    },
                    {
                        num: 12,
                        line: [
                            {
                                id: "t94c1a",
                                lemma: "le",
                                pos: "DETdef",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: "L’",
                            },
                            {
                                id: "t95c1a",
                                lemma: "estoire1",
                                pos: "NOMcom",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: "ystoire",
                            },
                            {
                                id: "t96c1a",
                                lemma: "estre1",
                                pos: "VERcjg",
                                msd: "MODE=ind|TEMPS=psp|PERS.=3|NOMB.=s",
                                text: "fu",
                            },
                            {
                                id: "t97c1a",
                                lemma: "trover",
                                pos: "VERppe",
                                msd: "NOMB.=s|GENRE=f|CAS=n",
                                text: "trovee",
                            },
                            {
                                id: "t98c1a",
                                lemma: "droit",
                                pos: "ADVgen",
                                msd: "MORPH=empty",
                                text: "droit",
                            },
                            {
                                id: "t99c1a",
                                lemma: "en1",
                                pos: "PRE",
                                msd: "MORPH=empty",
                                text: "en",
                            },
                            {
                                id: "t100c1a",
                                lemma: "un",
                                pos: "DETndf",
                                msd: "NOMB.=s|GENRE=m|CAS=r",
                                text: "un",
                            },
                            {
                                id: "t101c1a",
                                lemma: "dromont",
                                pos: "NOMcom",
                                msd: "NOMB.=s|GENRE=m|CAS=r",
                                text: "dromon",
                            },
                            {
                                id: "t102c1a",
                                lemma: ",",
                                pos: "PONfbl",
                                msd: "MORPH=empty",
                                text: ",",
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        n: "1v",
        notes: [
            {
                type: "nota_al_miniatore",
                place: "margine alto sx",
                line: [
                    {
                        id: "t1c",
                        lemma: "alexandre",
                        pos: "NOMpro",
                        msd: "SPEC=it|NOMB.=s|GENRE=f|CAS=n",
                        text: "alexandre",
                    },
                ],
            },
        ],
        lassas: [
            { n:"31", verses: [
               { 
                num: 300,  
                line: [
                  { id: "t1c4a", lemma:"ne1", pos:"ADVneg" , msd:"MORPH=empty", text: "N&#39;"},
                  { id: "t2c4a", lemma:"i2", pos:"PROadv" , msd:"MORPH=empty", text: "i"},
                  { id: "t3c4a", lemma:"avoir", pos:"PRE" , msd:"MODE=ind|TEMPS=pst|PERS.=3|NOMB.=s", text: "a"},
                  { id: "t4c4a", lemma:"cel", pos:"PROdem" , msd:"NOMB.=s|GENRE=m|CAS=n", text: "celui"},
                  { id: "t5c4a", lemma:"ne1", pos:"ADVneg" , msd:"MORPH=empty", text: "ni"},
                  { id: "t6c4a", lemma:"il", pos:"PROper" , msd:"PERS.=3|NOMB.=s|GENRE=m|CAS=i", text: "li"},
                  { id: "t7c4a", lemma:"dire", pos:"VERcjg" , msd:"MODE=sub|TEMPS=pst|PERS.=3|NOMB.=s", text: "die"},
                  { id: "t8c4a", lemma:"salu", pos:"NOMcom" , msd:"NOMB.=s|GENRE=m|CAS=r", text: "saluz"},
                  { id: "t9c4a", lemma:".", pos:"PONfrt" , msd:"MORPH=empty", text: "."},
               ],
               },
               { num: 301,  line: [
                  { id:"t10c4a", lemma: "«", pos:"PONfbl" , msd:"MORPH=empty", text: "«"},
                  { id:"t11c4a", lemma: "roial2", pos:"ADJqua" , msd:"NOMB.=s|GENRE=m|CAS=n|DEGRE=p", text: "Reial"},
                  { id:"t12c4a", lemma: "!" ,pos:"PONfrt" , msd:"MORPH=empty", text: "!"},
                  { id:"t13c4a", lemma: "»", pos:"PONfbl" , msd:"MORPH=empty", text: "»"},
                  { id:"t14c4a", lemma: "soi1", pos:"PROper" , msd:"PERS.=3|NOMB.=s|GENRE=m|CAS=r", text: "s&#39;"},
                  { id:"t15c4a", lemma: "escrïer", pos:"VERcjg" , msd:"MODE=ind|TEMPS=pst|PERS.=3|NOMB.=s", text: "escrïent"},
                  { id:"t16c4a", lemma: "«", pos:"PONfbl" , msd:"MORPH=empty", text: "«"},
                  { id:"t17c4a", lemma: "nostre", pos:"DETpos" , msd:"PERS.=5|NOMB.=s|GENRE=m|CAS=n", text: "nostre"},
                  { id:"t18c4a", lemma: "seignor", pos:"NOMcom" , msd:"NOMB.=s|GENRE=m|CAS=n", text: "sire"},
                  { id:"t19c4a", lemma: "estre1", pos:"VERcjg" , msd:"MODE=ind|TEMPS=pst|PERS.=3|NOMB.=s", text: "est"},
                  { id:"t20c4a", lemma: "venir", pos:"VERppe" , msd:"NOMB.=s|GENRE=m|CAS=n", text: "venuz"},
                  { id:"t21c4a", lemma: "." ,pos:"PONfrt" , msd:"MORPH=empty", text: "."},
               ],
                },
               { num: 302, line: [
                  { id:"t22c4a", lemma:"»", pos:"PONfbl" , msd:"MORPH=empty", text: "»"},
                  { id:"t23c4a", lemma:"et", pos:"CONcoo" , msd:"MORPH=empty", text: "Et"},
                  { id:"t24c4a", lemma:"Alexandre", pos:"NOMpro" , msd:"NOMB.=s|GENRE=m|CAS=n", text: "Alexandre"},
                  { id:"t25c4a", lemma:"soi1", pos:"PROper" , msd:"PERS.=3|NOMB.=s|GENRE=m|CAS=r", text: "s&#39;"},
                  { id:"t26c4a", lemma:"en2", pos:"PROadv" , msd:"MORPH=empty", text: "en"},
                  { id:"t27c4a", lemma:"estre1", pos:"VERcjg" , msd:"MODE=ind|TEMPS=pst|PERS.=3|NOMB.=s", text: "est"},
                  { id:"t28c4a", lemma:"mout", pos:"ADVgen" , msd:"MORPH=empty", text: "mout"},
                  { id:"t29c4a", lemma:"iraistre", pos:"VERppe" , msd:"NOMB.=s|GENRE=m|CAS=n", text: "irascuz"},
                  { id:"t30c4a", lemma:",", pos:"PONfbl" , msd:"MORPH=empty", text: ","},
               ]
               },
            ],
            },
        ],
    },
];
